version: '3.9'

services:
  auth-postgres:
    image: postgres:16-alpine
    container_name: auth-postgres
    environment:
      POSTGRES_DB: auth-service
      POSTGRES_USER: user
      POSTGRES_PASSWORD:  ${AUTH_SERVICE_DB_PASSWORD}
    volumes:
      - auth_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d auth_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  user-postgres:
    image: postgres:16-alpine
    container_name: user-postgres
    environment:
      POSTGRES_DB: user-service
      POSTGRES_USER: user
      POSTGRES_PASSWORD: ${USER_SERVICE_DB_PASSWORD}
    volumes:
      - user_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d user_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  order-postgres:
    image: postgres:16-alpine
    container_name: order-postgres
    environment:
      POSTGRES_DB: order-service
      POSTGRES_USER: user
      POSTGRES_PASSWORD: ${ORDER_SERVICE_DB_PASSWORD}
    volumes:
      - order_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d order_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: redis
    command: redis-server --save 60 1 --loglevel warning
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

  authentication-service:
    build:
      context: ./authentication-service
      dockerfile: Dockerfile
    container_name: auth-service
    ports:
      - "8082:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://auth-postgres:5432/auth_db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=${AUTH_SERVICE_DB_PASSWORD}
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
    depends_on:
      auth-postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: user-service
    ports:
      - "8081:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://user-postgres:5432/user_db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=${USER_SERVICE_DB_PASSWORD}
      - SPRING_REDIS_HOST=redis
    depends_on:
      user-postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    container_name: order-service
    ports:
      - "8083:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://order-postgres:5432/order_db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=${ORDER_SERVICE_DB_PASSWORD}
      - SPRING_REDIS_HOST=redis
    depends_on:
      order-postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      - SPRING_REDIS_HOST=redis
    depends_on:
      - authentication-service
      - user-service
      - order-service

volumes:
  auth_postgres_data:
  user_postgres_data:
  order_postgres_data:
  redis_data: