spring:
  profiles:
    active: prod
#spring:
#  application:
#    name: api-gateway
#  cloud:
#    gateway:
#      routes:
#        - id: user-service
#          uri: lb://user-service
#          predicates:
#            - Path=/api/users/**
#          filters:
#            - AuthenticationFilter
#
#        - id: auth-service
#          uri: lb://authentication-service
#          predicates:
#            - Path=/api/auth/login
#
#        - id: order-service
#          uri: lb://order-service
#          predicates:
#            - Path=/api/orders/
#
#services:
#  auth-url: http://authentication-service:8082
#  user-url: http://user-service:8081
#
#jwt:
#  secret: "${JWT_SECRET}"