server:
  port: 8084

spring:
  application:
    name: payment-service

  data:
    mongodb:
      uri: mongodb://admin:${PAYMENT_SERVICE_DB_PASSWORD}@localhost:27017/paymentdb?authSource=admin
      database: paymentdb

  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: ${spring.application.name}-dev-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

random:
  api:
    url: https://www.randomnumberapi.com

mongock:
  migration-scan-package: com.plgdhd.paymentservice.migration
  enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: false
    fetch-registry: false

logging:
  level:
    com.plgdhd.paymentservice: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG