server:
  port: ${SERVER_PORT:8084}

spring:
  application:
    name: payment-service

  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/paymentdb}
      database: paymentdb

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

    consumer:
      group-id: ${spring.application.name}-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

random:
  api:
    url: ${RANDOM_API_URL:https://www.randomnumberapi.com}

mongock:
  migration-scan-package: com.plgdhd.paymentservice.migration
  enabled: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://eureka-server:8761/eureka}
    register-with-eureka: true
    fetch-registry: true

logging:
  level:
    com.plgdhd.paymentservice: INFO
    org.springframework: INFO