spring:
  application:
    name: payment-service
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/payments}
      database: paymentdb

  kafka:
    bootstrap-servers:
      - localhost:9092

    consumer:
      group-id: KafkaCourse-lecture6-ClickStream
      auto-offset-reset: earliest

    producer:
      client-id: KafkaCourse-lecture6-UserAction

    template:
      default-topic: KafkaCourse-UserAction-ClickStream

random:
  api:
    url: ${RANDOM_API_URL:https://www.randomnumberapi.com}

mongock:
  migration-scan-package: com.plgdhd.paymentservice.migration
  enabled: true

server:
  port: ${SERVER_PORT:8084}

#eureka:
#  client:
#    service-url:
#      defaultZone: ${EUREKA_URL:http://eureka-server:8761/eureka}

logging:
  level:
    com.plgdhd.paymentservice: INFO
    org.springframework: INFO

