spring:
  profiles:
    active: local
  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}
      database: ${MONGO_DB_NAME:payment-service}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
payment:
  externalApiUrl: ${PAYMENT_EXTERNAL_API_URL:https://api.publicapis.org/random?type=number}
