server:
  port: 8083

spring:
  config:
    activate:
      on-profile: prod

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    enabled: true

  datasource:
    url: jdbc:postgresql://${DB_HOST:order-postgres}:${DB_PORT:5432}/${DB_NAME:order_service}
    username: ${DB_USERNAME:user}
    password: ${DB_PASSWORD:order_password}
    driver-class-name: org.postgresql.Driver

user:
  service:
    url: ${USER_SERVICE_URL:http://user-service:8081/api/users}

resilience4j:
  circuitbreaker:
    instances:
      userService:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 30s
        automaticTransitionFromOpenToHalfOpenEnabled: true

  retry:
    instances:
      userService:
        maxAttempts: 3
        waitDuration: 500ms
