server:
  port: 0

spring:
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
      client:
        config:
          default:
            connect-timeout: 100
            read-timeout: 100

  liquibase:
    enabled: false

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        jdbc:
          lob:
            non_contextual_creation: true

  datasource:
    url: jdbc:tc:postgresql:16:///testdb
    username: test
    password: test
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    hikari:
      maximum-pool-size: 5
      connection-timeout: 30000
      initialization-fail-timeout: 60000

  test:
    context:
      cache:
        maxSize: 0

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration
      - org.springframework.boot.autoconfigure.task.TaskExecutionAutoConfiguration
      - org.springframework.boot.autoconfigure.task.TaskSchedulingAutoConfiguration

resilience4j:
  circuitbreaker:
    instances:
      userService:
        slidingWindowSize: 2
        minimumNumberOfCalls: 2
        failureRateThreshold: 50
        waitDurationInOpenState: 500ms
        automaticTransitionFromOpenToHalfOpenEnabled: true
  retry:
    instances:
      userService:
        maxAttempts: 1
        waitDuration: 50ms

logging:
  level:
    com.plgdhd.orderservice: WARN
    org.springframework: WARN
    org.testcontainers: WARN
    com.github.tomakehurst.wiremock: WARN