name: Payment Microservices CI/CD

on:
  push:
    branches: [ main, develop, feature/* ]
  pull_request:
    branches: [ main ]

jobs:
  user-service-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: user-service

    services:
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 5s
          --health-timeout 3s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven

      - name: Build & Test User Service with Coverage
        run: mvn clean verify -B

      - name: Upload User Service JaCoCo report
        uses: actions/upload-artifact@v4
        with:
          name: user-jacoco-report
          path: user-service/target/site/jacoco/

  order-service-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: order-service

    services:
      postgres:
        image: postgres:16-alpine
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 5s
          --health-timeout 3s
          --health-retries 5
          env:
            POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
            POSTGRES_USER: postgres
            POSTGRES_DB: testdb 

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven

      - name: Build & Test Order Service with Coverage
        run: mvn clean verify -B

      - name: Upload Order Service JaCoCo report
        uses: actions/upload-artifact@v4
        with:
          name: order-jacoco-report
          path: order-service/target/site/jacoco/

  sonarqube:
    needs: [user-service-test, order-service-test]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven

      - name: Download coverage artifacts
        uses: actions/download-artifact@v4
        with:

          path: .

      - name: Compile project
        run: mvn clean compile -B

      - name: Run SonarQube analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn sonar:sonar \
            -Dsonar.token=$SONAR_TOKEN \
            -Dsonar.projectKey=Plgdhd_Payment-microservices \
            -Dsonar.organization=plgdhd \
            -Dsonar.host.url=https://sonarcloud.io \
            \
            -Dsonar.coverage.jacoco.xmlReportPaths=user-service/target/site/jacoco/jacoco.xml,order-service/target/site/jacoco/jacoco.xml \
            \
            -Dsonar.java.binaries=user-service/target/classes,order-service/target/classes